### ISSUE TITLE
Contra 3 does not work on real SA1 cart

### ISSUE THREAD

**Issue by badass-boss** [VitorVilela7/SA1-Root#15]
I tried Gradius 3 and Contra 3 on real SA1 cart with 128KB SRAM. I recorded both ROMs directly on cart. Gradius 3 worked for me, however Contra 3 refused to boot up at all for some reason. All I get is black screen. The cart configuration is exactly the same for both titles. Please help. Thanks in advance

**Comment by VitorVilela7** [comment]
Hi badass-boss, thank you for the issue!

That's indeed a known bug on my side and I'm working on a fix but I don't have an ETA yet. But stay tuned in here that I'll eventually post updates regarding the Contra III issue.

**Comment by badass-boss** [comment]
Thanks for your response. Fix for this would be greatly appreciated and I can cooperate and test updates on real SA1 cart

**Comment by BreakingHard** [comment]
Hi I have same problem. Contra on real cartridge starts with black screen and play conami logo sound than just black screen. I am sure that is no mistake with eprom or wiring because I done with same eprom chip and pcb donor another game and its ok. I guess this can be sram problem. This is not rom problem also - same game rom is running ok on flash cartridge on real snes, but on reproduction not. There is no 128kb RAM SA-1 cartridges, You can find 256kb ram cartridges as the donor, another options 64kb sram which is not comparable with this rom. So maybe 128kb sram is the problem. I tried to attach upper address of sram to ground to fix it as 128kb but its not help.

**Comment by CristianCG86** [comment]
I do some tests and I got the following conclusions. On a real cartridge not works, but on the FXPAK works correctly
¿What diferencies have the SA1 implementation of the FXPAK between the real SA1 hardware?

**Comment by jon-nielsen** [comment]
If help is needed for testing, I also have prepared some SA-1 donors which could run this.
